### PR TITLE
ot_flash: Add program/erase, memory protection, multi-word ops, FIFO watermarks & fixes

### LINKED ISSUE #126: Add support for writing to internal flash

### PR DESCRIPTION
**Pull request by AlexJones0**
This PR contains a lot of changes - I recommend reviewing by commit. More details about each change are in the commit messages & comments. A list of remaining unimplemented features has been added to the documentation on the file itself.

This PR does most of the work to get Earlgrey's Flash Controller to a full implementation; the main missing features now are scrambling/ECC/ICVs and alerts. In summary, this PR:
 - Adds program operation support, including program resolution & type errors.
 - Adds erase operation support (both page/bank erase).
 - Adds logic to allow for correct multi-word reads (current multi-word reads may be wrong, see the desc. of 99dad461299e5dc1015a5f4ac49c17937fb710f5)
 - Adds memory protection functionality (info pages, data regions and bank erase protection)
 - Fixes FIFO resets and adds watermark (fifo_lvl) functionality 
 - Fixes register description and RW type mismatches
 - Implements missing register writes
 - Fixes disable functionality
 - Adds "partway" erase suspend support.
 - Adds documentation for missing functionality.

This PR has been tested against [`master`](https://github.com/lowRISC/opentitan/commits/32b1337496ebd8b76c9538a79c37d34122c35868/) on OpenTitan via Bazel by overriding the QEMU binary:
| Test | `ot-earlgrey-9.2.0` result | New result |
| :---         |     :---:      |    :---:     |
| flash_ctrl_clock_freqs_test | **FAIL** | **PASS** |
| flash_ctrl_idle_low_power_test | **FAIL** | **FAIL** |
| flash_ctrl_info_access_lc_dev | **FAIL** | **FAIL** |
| flash_ctrl_info_access_lc_dev_personalized | **FAIL** | **PASS** |
| flash_ctrl_info_access_lc_prod_end | **FAIL** | **PASS** |
| flash_ctrl_info_access_lc_prod_end_personalized | **FAIL** | **PASS** |
| flash_ctrl_info_access_lc_prod_personalized | **FAIL** | **PASS** |
| flash_ctrl_info_access_lc_rma | **FAIL** | **PASS** |
| flash_ctrl_info_access_lc_test_unlocked0 | **FAIL** | **PASS** |
| flash_ctrl_mem_protection_test | **FAIL** | **PASS** |
| flash_ctrl_ops_test | **FAIL** | **PASS** |
| flash_ctrl_test | **FAIL** | **PASS** |
| flash_ctrl_write_clear_test | **FAIL** | **PASS** |
| rom_e2e_flash_ctrl_init | **FAIL** | **PASS** |

The failure in `flash_ctrl_idle_low_power_test` is because the reset reason is low power instead of POR; this is probably an issue in another block (rstmgr/pwrmgr etc.). I'm not sure where the failure in `flash_ctrl_info_access_lc_dev` is. The test just fails to boot, so this might be an OTP issue or maybe this test needs additional flags/parameters that I'm not aware of.

### CODE REVIEW

File: hw/opentitan/ot_flash.c [hunk 1]
```diff
@@ -866,78 +867,98 @@ static void ot_flash_op_complete(OtFlashState *s)
...
+
+static unsigned ot_flash_next_data_address(OtFlashState *s)
+{
+    OtFlashStorage *storage = &s->flash;
+    unsigned bank_size = storage->data_size;
+
+    /* offset the address by the number of proessed ops to get next addr */
+    unsigned op_offset = (s->op.count - s->op.remaining) * sizeof(uint32_t);
+    unsigned address = s->op.address + op_offset;
+    unsigned bank = address / bank_size;
```
Comment (jwnrt) [inline hw/opentitan/ot_flash.c:1154]: Could we add a bounds check for the bank please?

**Review by jwnrt — APPROVED** [review]

File: hw/opentitan/ot_flash.c (hunk 1 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c:1154]: This used to exist via the sanity check but I dropped this in favour of the more granular guest errors in the `ot_flash_next_info_address` function; I forgot that this case needs to also apply bounds checking to the data partition addresses. 

I've force pushed a change to add this check now - re-running the tests all the results are the same.

File: hw/opentitan/ot_flash.c [hunk 2]
```diff
@@ -1282,11 +1316,25 @@ static void ot_flash_regs_write(void *opaque, hwaddr addr, uint64_t val64,
...
         break;
+    case R_FAULT_STATUS: {
+        uint32_t rw0c_mask = (R_FAULT_STATUS_PHY_RELBL_ERR_MASK |
+                              R_FAULT_STATUS_PHY_STORAGE_ERR_MASK);
+        if (val32 & ~rw0c_mask) {
+            qemu_log_mask(LOG_GUEST_ERROR,
+                          "%s: Write to R/O field in register 0x%03" HWADDR_PRIx
+                          " (%s)\n",
+                          __func__, addr, REG_NAME(reg));
+            break;
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: I'm not sure about the break: the HW still needs to be updated with the valid value, and the invalid ones discarded. I do not think the HW reject the whole write access in case some RO bits are set.

File: hw/opentitan/ot_flash.c [hunk 3]
```diff
@@ -1060,11 +1060,20 @@ static void ot_flash_regs_write(void *opaque, hwaddr addr, uint64_t val64,
...
-        val32 &= INTR_MASK;
-        s->regs[R_INTR_STATE] &= ~val32; /* RW1C */
+    case R_INTR_STATE: {
+        uint32_t rw1c_mask = INTR_CORR_ERR_MASK | INTR_OP_DONE_MASK;
+        if (val32 & ~rw1c_mask) {
+            qemu_log_mask(LOG_GUEST_ERROR,
+                          "%s: Write to R/O field in register 0x%03" HWADDR_PRIx
+                          " (%s)\n",
+                          __func__, addr, REG_NAME(reg));
+            break;
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: Same issue here

File: hw/opentitan/ot_flash.c [hunk 4]
```diff
@@ -613,8 +613,26 @@ typedef enum {
     OP_NONE,
     OP_INIT,
     OP_READ,
+    OP_PROG,
+    OP_ERASE,
 } OtFlashOperation;
 
+typedef enum {
+    CONTROL_OP_READ = 0x0u,
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: enum are signed int

File: hw/opentitan/ot_flash.c [hunk 5]
```diff
@@ -642,6 +642,9 @@ enum {
 #define OP_INIT_DURATION_NS     1000000u /* 1 ms */
 #define ELFNAME_SIZE            256u
 #define OT_FLASH_READ_FIFO_SIZE 16u
+#define OT_TL_UL_D_WIDTH_BITS   32u
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: Maybe worth moving these two lines to `ot_common.h`

File: hw/opentitan/trace-events [hunk 6]
```diff
@@ -185,6 +185,9 @@ ot_flash_mem_read_out(uint32_t addr, unsigned size, uint32_t val, uint32_t pc) "
 ot_flash_op_complete(int op, bool success) "%d: %u"
 ot_flash_op_start(int op) "%d"
 ot_flash_set_error(int op, uint32_t err_code, uint32_t err_addr) "%d: err=%08x at addr=0x%06x"
+ot_flash_update_rd_watermark(unsigned val, unsigned watermark) "%u >= %u"
+ot_flash_update_prog_watermark(unsigned val, unsigned watermark) "%u <= %u"
+ot_flash_reset_fifo(const char *name) "reset %s fifo"
```
Comment (rivos-eblot) [inline hw/opentitan/trace-events]: nit pick: reset & fifo are already part of the function name

File: hw/opentitan/trace-events [hunk 7]
```diff
@@ -177,12 +177,14 @@ ot_entropy_src_update_generation(unsigned gennum) "%u"
 
 ot_flash_error(const char *func, int line, const char *err) "%s:%d %s"
 ot_flash_info(const char *func, int line, const char *msg, uint32_t value) "%s:%d %s: 0x%08x"
-ot_flash_info_part(uint32_t op_addr, unsigned bank, unsigned infosel, uint32_t addr) "op_addr 0x%06x bank %u infosel %u addr 0x%06x"
+ot_flash_info_part(uint32_t op_addr, unsigned count, unsigned remaining, unsigned bank, unsigned infosel, uint32_t addr) "op_addr 0x%06x count %u remaining %u bank %u infosel %u addr 0x%06x"
```
Comment (rivos-eblot) [inline hw/opentitan/trace-events]: although identical, callers seem to use `unsigned` for addresses, not `uint32_t`

File: hw/opentitan/ot_flash.c [hunk 8]
```diff
@@ -733,6 +733,20 @@ static void ot_flash_update_alerts(OtFlashState *s)
     }
 }
 
+static bool ot_flash_is_backend_writable(OtFlashState *s)
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: const

File: hw/opentitan/ot_flash.c [hunk 9]
```diff
@@ -733,6 +733,20 @@ static void ot_flash_update_alerts(OtFlashState *s)
...
+{
+    return (s->blk != NULL) && blk_is_writable(s->blk);
+}
+
+static bool ot_flash_write_backend(OtFlashState *s, const void *buffer,
+                                   unsigned offset, size_t size)
+{
+    // NOLINTBEGIN(clang-analyzer-optin.core.EnumCastOutOfRange)
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: C-ctyle comments prefered

File: hw/opentitan/ot_flash.c [hunk 10]
```diff
@@ -984,13 +998,93 @@ static void ot_flash_op_read(OtFlashState *s)
...
+        }
+        s->op.remaining--;
+
+        /*
+         * On encountering a multi-word write error, we must continue to empty
+         * the prog FIFO regardless, hence we retrieve the word to program
+         * before checking for errors.
+         */
+        if (s->op.failed) {
+            if (!fifo_empty) {
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c:1316]: Maybe add some `trace_` to help understanding the code path

File: hw/opentitan/ot_flash.c [hunk 11]
```diff
@@ -984,13 +998,93 @@ static void ot_flash_op_read(OtFlashState *s)
...
+                continue;
+            }
+            break;
+        }
+
+        /*
+         * Bits cannot be programmed back to 1 once programmed to 0; they must
+         * be erased instead.
+         */
+        dest[address] &= word;
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c:1329]: This case needs a `trace_` to help the guest code developer to track an unexpected result

File: hw/opentitan/ot_flash.c [hunk 12]
```diff
@@ -881,6 +881,23 @@ static void ot_flash_op_complete(OtFlashState *s)
     ot_flash_update_irqs(s);
 }
 
+static bool ot_flash_can_erase_bank(OtFlashState *s, unsigned bank)
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: const

File: hw/opentitan/ot_flash.c [hunk 13]
```diff
@@ -1074,6 +1091,101 @@ static void ot_flash_op_prog(OtFlashState *s)
     }
 }
 
+static void ot_flash_op_erase(OtFlashState *s)
+{
+    OtFlashStorage *storage = &s->flash;
+    unsigned address = s->op.info_part ? ot_flash_next_info_address(s) :
+                                         ot_flash_next_data_address(s);
+    if (s->op.failed) {
+        ot_flash_op_complete(s);
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c:1400]: maybe add a `trace_`

File: hw/opentitan/ot_flash.c [hunk 14]
```diff
@@ -1074,6 +1091,101 @@ static void ot_flash_op_prog(OtFlashState *s)
...
+    }
+
+    /* Try to erase all bits in the page/bank back to 1. */
+    if (s->op.erase_sel == ERASE_SEL_PAGE) {
+        uint32_t *dest = s->op.info_part ? storage->info : storage->data;
+        unsigned page_size = BYTES_PER_PAGE;
+        unsigned page_address = address - (address % page_size);
+        page_address /= sizeof(uint32_t); /* convert to word address */
+
+        memset(&dest[page_address], 0xFFu, page_size);
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: might be worth adding an assertion in case some computation fails and create an out of buffer error

File: hw/opentitan/ot_flash.c [hunk 15]
```diff
@@ -1074,6 +1091,101 @@ static void ot_flash_op_prog(OtFlashState *s)
...
+                                       page_size)) {
+                qemu_log_mask(LOG_GUEST_ERROR,
+                              "%s: cannot update flash backend\n", __func__);
+                ot_flash_set_error(s, R_ERR_CODE_PROG_ERR_MASK,
+                                   address * sizeof(uint32_t));
+                ot_flash_op_complete(s);
+                return;
+            }
+        }
+    } else { /* ERASE_SEL_BANK */
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: Maybe split this long function into two specialized ones

File: hw/opentitan/ot_flash.c [hunk 16]
```diff
@@ -1929,6 +2134,10 @@ static void ot_flash_csrs_write(void *opaque, hwaddr addr, uint64_t val64,
 
 static Property ot_flash_properties[] = {
     DEFINE_PROP_DRIVE("drive", OtFlashState, blk),
+    /* Optionally disable memory protection, as searching for valid memory
+    regions and checking their config can slow down regular operation. */
+    DEFINE_PROP_BOOL("no-protection", OtFlashState, disable_mem_protection,
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: If possible, try to keep the parameter name and the parametre string identical, _e.g._ "no-mem-prot"

File: hw/opentitan/ot_flash.c [hunk 17]
```diff
@@ -945,6 +1061,34 @@ static unsigned ot_flash_next_info_address(OtFlashState *s)
...
+    }
+    if (SHARED_FIELD_EX32(s->regs[info_page_cfg_reg], BANK_INFO_PAGE_CFG_EN) !=
+        OT_MULTIBITBOOL4_TRUE) {
+        return address; /* page config is disabled; so access is permitted. */
+    }
+    if (!ot_flash_info_page_cfg_op_enabled(s, info_page_cfg_reg)) {
+        qemu_log_mask(LOG_GUEST_ERROR,
+                      "%s: operation %u on info page %u in partition %u of "
+                      "bank %u is disabled by page config\n",
+                      __func__, s->op.kind, page, bank, info_partition);
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: General to all the commits, sorry to introduce this comment late:

I think it would be nice to have enum-to-string conversion array for log and trace messages, the same way it is done for registers (see also otp implementation for exampe). This is much clearer for the reader than to have to decode it when debugging I believe

File: hw/opentitan/ot_flash.c [hunk 18]
```diff
@@ -27,6 +28,16 @@
  *
  * Note: for now, only a minimalist subset of Power Manager device is
  *       implemented in order to enable OpenTitan's ROM boot to progress
+ *
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: I think the previous lines come from a bad copy 'n paste. Can you take this opportunity to delete them? Thanks

File: hw/opentitan/ot_flash.c [hunk 19]
```diff
@@ -727,6 +738,7 @@ static void ot_flash_update_irqs(OtFlashState *s)
 
 static void ot_flash_update_alerts(OtFlashState *s)
 {
+    /* Todo: implement non-test alert sources and update them here as well. */
```
Comment (rivos-eblot) [inline hw/opentitan/ot_flash.c]: nit pick: prefer `/* @todo text...*/` has it enables clang tools to grab them (as it parses some of the Doxygen syntax

**Review by rivos-eblot — CHANGES_REQUESTED** [review]
I do not know the flash controller behavior enough to check all the code, but it looks great. Thanks.

File: hw/opentitan/ot_flash.c (hunk 9 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: The other `// NOLINTNEXTLINE...` comments use `//` style comments (which goes against QEMU code styling convention), so I assumed that they were necessary for clang-analyzer. Is this not the case? If so, I'm happy to change this and other instances in this file, though I think this occurs in other blocks as well.

File: hw/opentitan/ot_flash.c (hunk 10 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c:1316]: I agree, the logic is quite entangled here but I couldn't see a nice way to simplify further. I'll add some traces to make this easier to follow.

File: hw/opentitan/ot_flash.c (hunk 11 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c:1329]: This makes sense, I figured that the tracing from `op_start` / `op_execute` / `ot_flash_info_part` / `ot_flash_data_part` would be sufficient tracing information, but I see how program/erase operations lead to state changes, and without tracing these directly it can be unclear when this happens (e.g. error in multi-words transactions). I'll add this.

File: hw/opentitan/ot_flash.c (hunk 13 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c:1400]: I think this should be fine; `ot_flash_next_info_address` and `ot_flash_next_data_address` have their own traces. If this case is executed (`s->op.failed`), then some error condition in one of these functions will have called `ot_flash_set_error` which has its own `trace_ot_flash_set_error` (and `op_complete` has its own trace). If you see an erase operation start, then error, then complete, with no actual data change trace (as mentioned above, I will add this for erase also), then that should be enough context?

Please do say if you disagree though, I'm not as sure when it comes to tracing so the comments are very helpful.

File: hw/opentitan/ot_flash.c (hunk 18 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: I thought as much as well but wasn't sure, as I know some of the blocks are quite connected. Will remove this.

File: hw/opentitan/ot_flash.c (hunk 9 above)
Comment (rivos-eblot) [reply hw/opentitan/ot_flash.c]: clang tool supports both syntax. It is just me having written stuff a long time ago, discovered contrainsts later, and failed to update the existing code :)
```
 rg -NI NOLINTNEXTLINE hw/opentitan | cut -d'(' -f1 | sed -E 's/^ +//' | sort | uniq -c
  15 /* NOLINTNEXTLINE */
   1 /* NOLINTNEXTLINE*/
   7 // NOLINTNEXTLINE
```

File: hw/opentitan/ot_flash.c (hunk 17 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: This sounds reasonable. Just to be clear, are you referring to [this](https://github.com/lowRISC/qemu/blob/04ae9343571f8bda7d9c137a70df46dbd10d8515/hw/opentitan/ot_otp_dj.c#L928-L1023), like for example `PART_NAME` [here](https://github.com/lowRISC/qemu/blob/04ae9343571f8bda7d9c137a70df46dbd10d8515/hw/opentitan/ot_otp_dj.c#L2095-L2096)?

File: hw/opentitan/ot_flash.c (hunk 2 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: I'm not sure either; both behaviours seem reasonable. I'll try and see if I can investigate the RTL further.

File: hw/opentitan/ot_flash.c (hunk 13 above)
Comment (rivos-eblot) [reply hw/opentitan/ot_flash.c:1400]: Ok, this should be enough.

traces are useful for two main purposes I believe:
1. Fix QEMU itself when some unexpected behavior is detected or corner cases encountered.
2. Help the OT developer to better understand a bug in his/her code, providing as much as introspection as possible from the "HW" side.

I never get the trace right the first time, it always takes several iterations to improve them. Sometimes there are too many of them, more often too few, and usually not at the best locations :)

File: hw/opentitan/ot_flash.c (hunk 2 above)
Comment (rivos-eblot) [reply hw/opentitan/ot_flash.c]: Most of the time from what I observed register bits are handled independently

File: hw/opentitan/ot_flash.c (hunk 17 above)
Comment (rivos-eblot) [reply hw/opentitan/ot_flash.c]: Yes, this kind of syntax. Thanks.

File: hw/opentitan/ot_flash.c (hunk 2 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: As far as I can tell from a cursory glance at [`hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv`](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv), this seems to be the case (with the prim_subreg updating independent fields), though I haven't checked this in detail. I'll remove these incorrect `break`s.

**Comment by rivos-eblot** [comment]
> The failure in `flash_ctrl_idle_low_power_test` is because the reset reason is low power instead of POR; this is probably an issue in another block (rstmgr/pwrmgr etc.). I'm not sure where the failure in `flash_ctrl_info_access_lc_dev` is. The test just fails to boot, so this might be an OTP issue or maybe this test needs additional flags/parameters that I'm not aware of.

1. `ot_clkmgr` is basically an empty shell at the moment. I'm still trying to figure out a way to implement it in a generic way as it is highly configurable and top-dependent (not a high priority though)
2. `ot_pwrmgr` handles _fast clock_ FSM, but the  _slow clock_ FSM is also mostly empty, as up to now we never had strong requirements to implement it.
3. I do not think we've added LC management to the embedded flash controller, since we've implemented OTP/LC much later then `ot_flash`, and have not really uses `ot_flash` since.

It is likely that many signals (and associated behavior) are missing at the moment.

File: hw/opentitan/ot_flash.c (hunk 9 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: My latest force push fixes this case and all the other cases that occur in `ot_flash.c`.

File: hw/opentitan/ot_flash.c (hunk 14 above)
Comment (AlexJones0) [reply hw/opentitan/ot_flash.c]: I've now added some basic bounds sanity check assertations to each of the buffer accesses in read/prog/erase in the latest force push.

**Comment by AlexJones0** [comment]
I believe my latest force push should have addressed all of the outstanding comments. The test results remain the same as the original post. Thanks for the reviews and detailed comments - I appreciate that this is quite a large PR to review.

File: include/hw/opentitan/ot_common.h [hunk 20]
```diff
@@ -35,6 +35,13 @@
 /* QEMU virtual timer to use for OpenTitan devices */
 #define OT_VIRTUAL_CLOCK QEMU_CLOCK_VIRTUAL
 
+/* ------------------------------------------------------------------------ */
```
Comment (rivos-eblot) [inline include/hw/opentitan/ot_common.h:39]: You also need to update the file caption (2025, etc.)

**Review by rivos-eblot — CHANGES_REQUESTED** [review]
one last thing :-)

**Review by rivos-eblot — APPROVED** [review]
LGTM

**Review by jwnrt — APPROVED** [review]
